# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
inhibit_all_warnings!
target 'MusicTest' do
  
  pod 'Masonry'
  pod 'ReactiveObjC'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'VODUpload'
  pod 'YYModel'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'AliPlayerSDK_iOS'
  pod 'SDCycleScrollView'
  use_frameworks!


end
